sonar.projectKey=music-school
sonar.projectName=Music School
sonar.sourceEncoding=UTF-8
sonar.sources=backend,frontend/src
sonar.tests=backend,frontend/src
sonar.test.inclusions=**/*_test.go,**/*.test.js
sonar.exclusions=**/*_test.go,**/*.test.js,**/node_modules/**,**/coverage/**
sonar.coverage.exclusions=frontend/src/main.js
sonar.go.coverage.reportPaths=backend/coverage.out
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.qualitygate.wait=true
