apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: school
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: traefik
  tls:
    - hosts: [school.CHANGE_ME]
      secretName: school-tls
  rules:
    - host: school.CHANGE_ME
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: { service: { name: frontend, port: { number: 80 } } }
