apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: school
resources:
  - app.yaml
  - database.yaml
  - ingress.yaml
images:
  - name: school-backend
    newName: ghcr.io/CHANGE_ME/music-school-backend
    newTag: latest
  - name: school-frontend
    newName: ghcr.io/CHANGE_ME/music-school-frontend
    newTag: latest
