apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: school
resources:
  - app.yaml
  - database.yaml
  - ingress.yaml
images:
  - name: school-backend
    newName: ghcr.io/waontest999/music-school-backend
    newTag: b391ec3e15337d934d94978c505979009b78f86b
  - name: school-frontend
    newName: ghcr.io/waontest999/music-school-frontend
    newTag: b391ec3e15337d934d94978c505979009b78f86b
