apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: music-school
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/WAonTest999/2026-devops-P4114-shelyagov_a_s.git
    targetRevision: main
    path: deploy/no-domain
  destination:
    server: https://kubernetes.default.svc
    namespace: school
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
