apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: school
resources:
  - ../app
patches:
  - patch: |-
      $patch: delete
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: school
  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "false"
